#!/usr/bin/env python3
"""Compute cost of the label-free rules U1 (lambda by agreement) and M3 (merge decision by disagreement) on E6 (Qwen2.5-1.5B).
Analytic forward-pass counts follow the frozen code (e6_decoder2/code/lam_confirm_e6.py: split() -> n_cal = min(200, n_eval // 2);
U1 uses the merged model's predictions at every lambda of the grid on the n_cal inputs of both tasks plus the single adapters'
predictions on the same inputs; M3's score Dhat_U = 1 - max_lambda agreement reuses the U1 table) and the stage-2 pipeline
(e6_decoder2/code/e6.py run_merges: TA at 7 lambdas on held-out (1,000/task) and eval sets, TIES at 4 lambdas on held-out plus 1-2 eval
passes, the gate likewise when active). Measured wall-clock comes only from e6_decoder2/results/timing_*.json and the per-pair "secs"
field of pair_results_*.jsonl; U1/M3 were computed post hoc from saved predictions, so no U1-only wall-clock or memory was measured.
Eval-set sizes: e6_lambda/data/pairs_unlabeled.csv (Qwen rows; n_eval = ncal + ntest), valid for E6 because tasks_e6.py uses the E4b
index logic unchanged. Output: analysis/compute_cost_u1_m3.md"""
import csv, json, statistics as st
from pathlib import Path
R = Path(__file__).resolve().parents[1]
G4, G7, NHOLD = 4, 7, 1000
n_eval, n_cal = {}, {}
for r in csv.DictReader(open(R / "e6_lambda/data/pairs_unlabeled.csv")):
    if r["backbone"] != "qwen": continue
    a, b = r["pair"].split("__")
    for t, j in ((a.split("@")[0], "1"), (b.split("@")[0], "2")):
        n = int(r["ncal" + j]) + int(r["ntest" + j])
        assert n_eval.setdefault(t, n) == n
        n_cal[t] = int(r["ncal" + j]); assert n_cal[t] == min(200, n // 2)
recs = []
for p in ("R0", "S1", "P"):
    seen = set()
    for l in open(R / f"e6_decoder2/results/pair_results_{p}.jsonl"):
        if not l.strip(): continue
        x = json.loads(l)
        if x["pair"] in seen: continue
        seen.add(x["pair"]); x["pop"] = p; recs.append(x)
rows = []
for x in recs:
    t1, t2 = x["t1_task"], x["t2_task"]; c = n_cal[t1] + n_cal[t2]; e = n_eval[t1] + n_eval[t2]; h = 2 * NHOLD
    ta = G7 * (h + e)
    ties = G4 * h + (1 if x["lam_TIES_own"] == x["lam_selected"] else 2) * e
    gate = (G4 * h + (1 if x["lam_GATE_own"] == x["lam_selected"] else 2) * e) if x["gate_active"] else 0
    rows.append(dict(pop=x["pop"], cal=c, u1_g4=G4 * c, u1_g7=G7 * c, single=c, lab_g4=G4 * h, stage2=ta + ties + gate, secs=x["secs"]))
N = len(rows)
med = lambda k: st.median(r[k] for r in rows)
frac = [r["u1_g4"] / r["stage2"] for r in rows]
out = ["# Compute cost of U1 and M3 on E6 (Qwen2.5-1.5B; analytic counts + measured pipeline wall-clock)", "",
       "Generated by analysis/compute_cost_u1_m3.py. Counts are forward passes of one input through the merged (or single-adapter) model.", "",
       f"- Tasks: {len(n_cal)}; unlabeled calibration inputs per task n_cal = min(200, floor(n_eval/2)): " + ", ".join(f"{t} {n_cal[t]}" for t in sorted(n_cal)),
       f"- Cross-task pairs scored by U1/M3: {N}",
       f"- Unlabeled inputs per pair (both tasks): max {max(r['cal'] for r in rows)}, min {min(r['cal'] for r in rows)}",
       f"- U1 merged-model forward passes per pair, grid G4 ({G4} lambdas): max {max(r['u1_g4'] for r in rows)}, min {min(r['u1_g4'] for r in rows)}; total over {N} pairs {sum(r['u1_g4'] for r in rows)}",
       f"- U1 merged-model forward passes per pair, grid G7 ({G7} lambdas): max {max(r['u1_g7'] for r in rows)}; total {sum(r['u1_g7'] for r in rows)}",
       f"- Single-adapter reference passes per pair: max {max(r['single'] for r in rows)} (computed once per adapter and reusable across pairs)",
       "- M3 extra forward passes: 0 (Dhat_U = 1 - max over lambda of the U1 agreement table)",
       f"- Labeled held-out tuning on G4 (reference): {G4 * 2 * NHOLD} merged-model passes per pair on {2 * NHOLD} labeled held-out training examples, plus {2 * NHOLD} single-adapter passes per pair",
       f"- Full E6 stage-2 pipeline per pair (TA x7 lambdas on held-out + eval, TIES, gate when active): median {med('stage2'):.0f} merged-model passes; U1 (G4) share of these passes: median {100 * st.median(frac):.1f}%, max {100 * max(frac):.1f}%",
       "", "## Measured wall-clock (full stage-2 pipeline, one RTX 4070 Ti SUPER; not U1-specific)", ""]
for p in ("R0", "S1", "P"):
    s = [r["secs"] for r in rows if r["pop"] == p]
    tot = json.loads((R / f"e6_decoder2/results/timing_{p}.json").read_text())["stage2_gpu_wall_s"]
    out.append(f"- {p}: {len(s)} pairs; stage-2 wall-clock {tot:.1f} s total; per pair median {st.median(s):.1f} s (min {min(s):.1f}, max {max(s):.1f})")
out += ["", "U1-only wall-clock and peak GPU memory of U1/M3 were not measured (the rules were evaluated post hoc on saved predictions)."]
(R / "analysis/compute_cost_u1_m3.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
