#!/usr/bin/env python3
"""Verbatim extract of the E6 pre-registration passages that define the label-free rules (sec. 6c) and the
pre-flight memory measurement (sec. 7), so that the manuscript can cite them; plus one derived rounding.
Source: e6_decoder2/artifacts_mirror/PREREG_E6.md (hash-stamped; not modified). Output: analysis/e6_prereg_extract.md"""
import re
from pathlib import Path
R = Path(__file__).resolve().parents[1]
src = (R / "e6_decoder2/artifacts_mirror/PREREG_E6.md").read_text()
a = src.index("### 6c."); b = src.index("## 7.")
sec6c = src[a:b].rstrip()
pre = [l for l in src.splitlines() if "peaked at" in l or "Training peak" in l]
thr = re.search(r"D̂_U ≥ \*\*([0-9.]+)\*\*", sec6c).group(1)
out = ["# E6 pre-registration extract: label-free rules (verbatim) and pre-flight memory", "",
       "Generated by analysis/e6_prereg_extract.py from e6_decoder2/artifacts_mirror/PREREG_E6.md (verbatim; not edited).", "",
       "## Section 6c (verbatim)", "", sec6c, "",
       "## Pre-flight smoke run, section 7 (verbatim; throwaway 20-step adapters, not study evidence)", ""] + pre + ["",
       "## Derived", "", f"- Frozen H-M3acc threshold {thr} rounded to four decimals: {float(thr):.4f}; to three decimals: {float(thr):.3f}.", ""]
(R / "analysis/e6_prereg_extract.md").write_text("\n".join(out))
print("written", len(out), "lines; threshold", thr)
